# Generated by Django 3.0.7 on 2020-06-26 12:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=80)),
                ('property_type', models.CharField(max_length=80)),
                ('contract_type', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bedroom_num', models.IntegerField()),
                ('bathroom_num', models.IntegerField()),
                ('vacancy', models.CharField(max_length=80)),
                ('valid', models.CharField(max_length=80)),
                ('date', models.DateField(default=datetime.datetime(2020, 6, 26, 12, 11, 13, 329972, tzinfo=utc), verbose_name='date_posted')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zim_Estate_App.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=80)),
                ('path', models.CharField(max_length=120)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zim_Estate_App.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('phone_number', models.CharField(max_length=15)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zim_Estate_App.Property')),
            ],
        ),
    ]
