# Generated by Django 3.0.7 on 2020-06-28 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 28, 13, 7, 51, 126351, tzinfo=utc), verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='property',
            name='vacancy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='valid',
            field=models.BooleanField(),
        ),
    ]
