# Generated by Django 3.0.7 on 2020-06-28 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0002_auto_20200628_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='vacancy',
            new_name='is_valid',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='valid',
            new_name='vacant',
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 28, 13, 15, 59, 437263, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
