# Generated by Django 3.0.7 on 2020-07-02 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0003_auto_20200628_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 17, 37, 40, 560839, tzinfo=utc), verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This Email is already in use'}, max_length=80, unique=True),
        ),
    ]
