# Generated by Django 3.0.7 on 2020-07-05 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0005_auto_20200705_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 5, 10, 8, 51, 757838, tzinfo=utc), verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='re_password',
            field=models.CharField(max_length=20),
        ),
    ]
