# Generated by Django 3.0.7 on 2020-07-05 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0007_auto_20200705_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='re_password',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 5, 10, 26, 10, 966887, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
