# Generated by Django 3.0.7 on 2020-07-07 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0008_auto_20200705_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=280)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('subject', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 7, 12, 38, 41, 380595, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
