# Generated by Django 3.0.7 on 2020-07-08 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0009_auto_20200707_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to='static/Zim_Estate_App/posts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 8, 14, 43, 25, 160097, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
