# Generated by Django 3.0.7 on 2020-07-08 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0010_auto_20200708_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/Zim_Estate_App/posts'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/Zim_Estate_App/posts'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/Zim_Estate_App/posts'),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 8, 14, 56, 22, 611138, tzinfo=utc), verbose_name='date_posted'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
