# Generated by Django 3.0.7 on 2020-07-09 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0011_auto_20200708_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 9, 17, 24, 42, 693740, tzinfo=utc), verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='vacant',
            field=models.BooleanField(default=True),
        ),
    ]
