# Generated by Django 3.0.7 on 2020-07-10 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0014_auto_20200710_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 10, 12, 32, 15, 713671, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
