# Generated by Django 3.0.7 on 2020-07-10 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0015_auto_20200710_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 10, 12, 45, 40, 995187, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
