# Generated by Django 3.0.7 on 2020-07-10 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0017_auto_20200710_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='surname',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 10, 14, 30, 59, 110440, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
