# Generated by Django 3.0.7 on 2020-07-10 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0018_auto_20200710_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='message',
            field=models.CharField(default=None, max_length=320),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 10, 14, 45, 49, 274581, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
