# Generated by Django 3.0.7 on 2020-07-24 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0020_auto_20200719_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='property',
            name='suburb',
            field=models.CharField(default='location', max_length=80),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 24, 12, 32, 38, 991730, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
