# Generated by Django 3.0.7 on 2020-07-24 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0021_auto_20200724_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 24, 15, 16, 7, 250870, tzinfo=utc), verbose_name='date_posted'),
        ),
    ]
