# Generated by Django 3.0.7 on 2020-08-17 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0022_auto_20200724_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 12, 40, 16, 220267, tzinfo=utc), verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='property',
            name='suburb',
            field=models.CharField(default='location(Suburb)', max_length=80),
        ),
    ]
