# Generated by Django 3.0.7 on 2020-08-19 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0023_auto_20200817_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 18, 9, 32, 663239), verbose_name='date_posted'),
        ),
    ]
