# Generated by Django 3.0.7 on 2020-08-22 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zim_Estate_App', '0024_auto_20200819_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 22, 12, 25, 7, 62732), verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='property',
            name='interested',
            field=models.IntegerField(default=1),
        ),
    ]
